<!ELEMENT rutas (ruta+)>
<!ELEMENT ruta (nombre, tipo, transporte, duracion, agencia, descripcion, personas, inicio, referencias, hitos)>
<!ATTLIST ruta recomendacion CDATA #REQUIRED>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT transporte (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT agencia (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT personas (#PCDATA)>

<!ELEMENT inicio (lugar, direccion, coordenadas)>
<!ELEMENT lugar (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT coordenadas (latitud, longitud, altitud)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>

<!ELEMENT referencias (ref+)>
<!ELEMENT ref (#PCDATA)>

<!ELEMENT hitos (hito+)>
<!ELEMENT hito (nombre, descripcion, coordenadas, distancia, imagenes)>
<!ELEMENT coordenadas EMPTY>
<!ATTLIST coordenadas lat CDATA #REQUIRED lon CDATA #REQUIRED alt CDATA #REQUIRED>

<!ELEMENT distancia (#PCDATA)>
<!ATTLIST distancia unidad CDATA #REQUIRED>

<!ELEMENT imagenes (img+)>
<!ELEMENT img (#PCDATA)>

<!ELEMENT planimetria EMPTY>
<!ATTLIST planimetria archivo CDATA #REQUIRED>

<!ELEMENT altimetria EMPTY>
<!ATTLIST altimetria archivo CDATA #REQUIRED>

<!ELEMENT fechaInicio (#PCDATA)>
<!ELEMENT horaInicio (#PCDATA)>

